// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qwibi/auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QPBxAuthRequest struct {
	// Types that are valid to be assigned to Auth:
	//	*QPBxAuthRequest_Anonym
	//	*QPBxAuthRequest_Basic
	Auth                 isQPBxAuthRequest_Auth `protobuf_oneof:"auth"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QPBxAuthRequest) Reset()         { *m = QPBxAuthRequest{} }
func (m *QPBxAuthRequest) String() string { return proto.CompactTextString(m) }
func (*QPBxAuthRequest) ProtoMessage()    {}
func (*QPBxAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_033c32f58963f501, []int{0}
}

func (m *QPBxAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QPBxAuthRequest.Unmarshal(m, b)
}
func (m *QPBxAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QPBxAuthRequest.Marshal(b, m, deterministic)
}
func (m *QPBxAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QPBxAuthRequest.Merge(m, src)
}
func (m *QPBxAuthRequest) XXX_Size() int {
	return xxx_messageInfo_QPBxAuthRequest.Size(m)
}
func (m *QPBxAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QPBxAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QPBxAuthRequest proto.InternalMessageInfo

type isQPBxAuthRequest_Auth interface {
	isQPBxAuthRequest_Auth()
}

type QPBxAuthRequest_Anonym struct {
	Anonym *QPBxAnonymAuth `protobuf:"bytes,1,opt,name=anonym,proto3,oneof"`
}

type QPBxAuthRequest_Basic struct {
	Basic *QPBxBasicAuth `protobuf:"bytes,2,opt,name=basic,proto3,oneof"`
}

func (*QPBxAuthRequest_Anonym) isQPBxAuthRequest_Auth() {}

func (*QPBxAuthRequest_Basic) isQPBxAuthRequest_Auth() {}

func (m *QPBxAuthRequest) GetAuth() isQPBxAuthRequest_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *QPBxAuthRequest) GetAnonym() *QPBxAnonymAuth {
	if x, ok := m.GetAuth().(*QPBxAuthRequest_Anonym); ok {
		return x.Anonym
	}
	return nil
}

func (m *QPBxAuthRequest) GetBasic() *QPBxBasicAuth {
	if x, ok := m.GetAuth().(*QPBxAuthRequest_Basic); ok {
		return x.Basic
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QPBxAuthRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QPBxAuthRequest_Anonym)(nil),
		(*QPBxAuthRequest_Basic)(nil),
	}
}

type QPBxAuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QPBxAuthResponse) Reset()         { *m = QPBxAuthResponse{} }
func (m *QPBxAuthResponse) String() string { return proto.CompactTextString(m) }
func (*QPBxAuthResponse) ProtoMessage()    {}
func (*QPBxAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_033c32f58963f501, []int{1}
}

func (m *QPBxAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QPBxAuthResponse.Unmarshal(m, b)
}
func (m *QPBxAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QPBxAuthResponse.Marshal(b, m, deterministic)
}
func (m *QPBxAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QPBxAuthResponse.Merge(m, src)
}
func (m *QPBxAuthResponse) XXX_Size() int {
	return xxx_messageInfo_QPBxAuthResponse.Size(m)
}
func (m *QPBxAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QPBxAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QPBxAuthResponse proto.InternalMessageInfo

func (m *QPBxAuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type QPBxAnonymAuth struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QPBxAnonymAuth) Reset()         { *m = QPBxAnonymAuth{} }
func (m *QPBxAnonymAuth) String() string { return proto.CompactTextString(m) }
func (*QPBxAnonymAuth) ProtoMessage()    {}
func (*QPBxAnonymAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_033c32f58963f501, []int{2}
}

func (m *QPBxAnonymAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QPBxAnonymAuth.Unmarshal(m, b)
}
func (m *QPBxAnonymAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QPBxAnonymAuth.Marshal(b, m, deterministic)
}
func (m *QPBxAnonymAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QPBxAnonymAuth.Merge(m, src)
}
func (m *QPBxAnonymAuth) XXX_Size() int {
	return xxx_messageInfo_QPBxAnonymAuth.Size(m)
}
func (m *QPBxAnonymAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_QPBxAnonymAuth.DiscardUnknown(m)
}

var xxx_messageInfo_QPBxAnonymAuth proto.InternalMessageInfo

type QPBxBasicAuth struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QPBxBasicAuth) Reset()         { *m = QPBxBasicAuth{} }
func (m *QPBxBasicAuth) String() string { return proto.CompactTextString(m) }
func (*QPBxBasicAuth) ProtoMessage()    {}
func (*QPBxBasicAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_033c32f58963f501, []int{3}
}

func (m *QPBxBasicAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QPBxBasicAuth.Unmarshal(m, b)
}
func (m *QPBxBasicAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QPBxBasicAuth.Marshal(b, m, deterministic)
}
func (m *QPBxBasicAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QPBxBasicAuth.Merge(m, src)
}
func (m *QPBxBasicAuth) XXX_Size() int {
	return xxx_messageInfo_QPBxBasicAuth.Size(m)
}
func (m *QPBxBasicAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_QPBxBasicAuth.DiscardUnknown(m)
}

var xxx_messageInfo_QPBxBasicAuth proto.InternalMessageInfo

func (m *QPBxBasicAuth) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *QPBxBasicAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*QPBxAuthRequest)(nil), "QPBxAuthRequest")
	proto.RegisterType((*QPBxAuthResponse)(nil), "QPBxAuthResponse")
	proto.RegisterType((*QPBxAnonymAuth)(nil), "QPBxAnonymAuth")
	proto.RegisterType((*QPBxBasicAuth)(nil), "QPBxBasicAuth")
}

func init() {
	proto.RegisterFile("qwibi/auth.proto", fileDescriptor_033c32f58963f501)
}

var fileDescriptor_033c32f58963f501 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2c, 0xcf, 0x4c,
	0xca, 0xd4, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xca, 0xe1, 0xe2,
	0x0f, 0x0c, 0x70, 0xaa, 0x70, 0x2c, 0x2d, 0xc9, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0xd2, 0xe4, 0x62, 0x4b, 0xcc, 0xcb, 0xcf, 0xab, 0xcc, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36,
	0xe2, 0xd7, 0x03, 0xab, 0x00, 0x0b, 0x81, 0xd4, 0x79, 0x30, 0x04, 0x41, 0x15, 0x08, 0xa9, 0x71,
	0xb1, 0x26, 0x25, 0x16, 0x67, 0x26, 0x4b, 0x30, 0x81, 0x55, 0xf2, 0x81, 0x55, 0x3a, 0x81, 0x44,
	0xa0, 0x0a, 0x21, 0xd2, 0x4e, 0x6c, 0x5c, 0x2c, 0x20, 0x3b, 0x95, 0x34, 0xb8, 0x04, 0x10, 0xb6,
	0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0xe4, 0x67, 0xa7, 0xe6, 0x81,
	0x6d, 0xe3, 0x0c, 0x82, 0x70, 0x94, 0x04, 0xb8, 0xf8, 0x50, 0x6d, 0x55, 0x72, 0xe4, 0xe2, 0x45,
	0x31, 0x1d, 0xa4, 0x31, 0x27, 0x3f, 0x3d, 0x13, 0xae, 0x11, 0xcc, 0x11, 0x92, 0xe2, 0xe2, 0x28,
	0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x01, 0xbb, 0x8a, 0x33, 0x08, 0xce, 0x77, 0xe2, 0x8d,
	0xe2, 0x06, 0xfb, 0xda, 0x1a, 0x4c, 0x26, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0x26, 0x47, 0x8d, 0x16, 0x01, 0x00, 0x00,
}
