// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: qwibi/geojson.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QPBxFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Geometry:
	//	*QPBxFeature_Point
	//	*QPBxFeature_Line
	Geometry   isQPBxFeature_Geometry `protobuf_oneof:"geometry"`
	Properties *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
}

func (x *QPBxFeature) Reset() {
	*x = QPBxFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qwibi_geojson_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxFeature) ProtoMessage() {}

func (x *QPBxFeature) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_geojson_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxFeature.ProtoReflect.Descriptor instead.
func (*QPBxFeature) Descriptor() ([]byte, []int) {
	return file_qwibi_geojson_proto_rawDescGZIP(), []int{0}
}

func (m *QPBxFeature) GetGeometry() isQPBxFeature_Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (x *QPBxFeature) GetPoint() *QPBxPoint {
	if x, ok := x.GetGeometry().(*QPBxFeature_Point); ok {
		return x.Point
	}
	return nil
}

func (x *QPBxFeature) GetLine() *QPBxLine {
	if x, ok := x.GetGeometry().(*QPBxFeature_Line); ok {
		return x.Line
	}
	return nil
}

func (x *QPBxFeature) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type isQPBxFeature_Geometry interface {
	isQPBxFeature_Geometry()
}

type QPBxFeature_Point struct {
	Point *QPBxPoint `protobuf:"bytes,1,opt,name=point,proto3,oneof"`
}

type QPBxFeature_Line struct {
	Line *QPBxLine `protobuf:"bytes,2,opt,name=line,proto3,oneof"`
}

func (*QPBxFeature_Point) isQPBxFeature_Geometry() {}

func (*QPBxFeature_Line) isQPBxFeature_Geometry() {}

type QPBxFeatureCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features []*QPBxFeature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
}

func (x *QPBxFeatureCollection) Reset() {
	*x = QPBxFeatureCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qwibi_geojson_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxFeatureCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxFeatureCollection) ProtoMessage() {}

func (x *QPBxFeatureCollection) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_geojson_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxFeatureCollection.ProtoReflect.Descriptor instead.
func (*QPBxFeatureCollection) Descriptor() ([]byte, []int) {
	return file_qwibi_geojson_proto_rawDescGZIP(), []int{1}
}

func (x *QPBxFeatureCollection) GetFeatures() []*QPBxFeature {
	if x != nil {
		return x.Features
	}
	return nil
}

type QPBxPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []float64 `protobuf:"fixed64,1,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *QPBxPoint) Reset() {
	*x = QPBxPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qwibi_geojson_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxPoint) ProtoMessage() {}

func (x *QPBxPoint) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_geojson_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxPoint.ProtoReflect.Descriptor instead.
func (*QPBxPoint) Descriptor() ([]byte, []int) {
	return file_qwibi_geojson_proto_rawDescGZIP(), []int{2}
}

func (x *QPBxPoint) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type QPBxLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*QPBxPoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *QPBxLine) Reset() {
	*x = QPBxLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qwibi_geojson_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxLine) ProtoMessage() {}

func (x *QPBxLine) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_geojson_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxLine.ProtoReflect.Descriptor instead.
func (*QPBxLine) Descriptor() ([]byte, []int) {
	return file_qwibi_geojson_proto_rawDescGZIP(), []int{3}
}

func (x *QPBxLine) GetPoints() []*QPBxPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_qwibi_geojson_proto protoreflect.FileDescriptor

var file_qwibi_geojson_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x77, 0x69, 0x62, 0x69, 0x2f, 0x67, 0x65, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x51, 0x50, 0x42, 0x78, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x69, 0x6e, 0x65,
	0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x42, 0x0a, 0x0a, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x22, 0x41, 0x0a,
	0x15, 0x51, 0x50, 0x42, 0x78, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x22, 0x2d, 0x0a, 0x09, 0x51, 0x50, 0x42, 0x78, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22,
	0x2e, 0x0a, 0x08, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x51, 0x50,
	0x42, 0x78, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qwibi_geojson_proto_rawDescOnce sync.Once
	file_qwibi_geojson_proto_rawDescData = file_qwibi_geojson_proto_rawDesc
)

func file_qwibi_geojson_proto_rawDescGZIP() []byte {
	file_qwibi_geojson_proto_rawDescOnce.Do(func() {
		file_qwibi_geojson_proto_rawDescData = protoimpl.X.CompressGZIP(file_qwibi_geojson_proto_rawDescData)
	})
	return file_qwibi_geojson_proto_rawDescData
}

var file_qwibi_geojson_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_qwibi_geojson_proto_goTypes = []interface{}{
	(*QPBxFeature)(nil),           // 0: QPBxFeature
	(*QPBxFeatureCollection)(nil), // 1: QPBxFeatureCollection
	(*QPBxPoint)(nil),             // 2: QPBxPoint
	(*QPBxLine)(nil),              // 3: QPBxLine
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
}
var file_qwibi_geojson_proto_depIdxs = []int32{
	2, // 0: QPBxFeature.point:type_name -> QPBxPoint
	3, // 1: QPBxFeature.line:type_name -> QPBxLine
	4, // 2: QPBxFeature.properties:type_name -> google.protobuf.Struct
	0, // 3: QPBxFeatureCollection.features:type_name -> QPBxFeature
	2, // 4: QPBxLine.points:type_name -> QPBxPoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_qwibi_geojson_proto_init() }
func file_qwibi_geojson_proto_init() {
	if File_qwibi_geojson_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qwibi_geojson_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qwibi_geojson_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxFeatureCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qwibi_geojson_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qwibi_geojson_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_qwibi_geojson_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*QPBxFeature_Point)(nil),
		(*QPBxFeature_Line)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qwibi_geojson_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_geojson_proto_goTypes,
		DependencyIndexes: file_qwibi_geojson_proto_depIdxs,
		MessageInfos:      file_qwibi_geojson_proto_msgTypes,
	}.Build()
	File_qwibi_geojson_proto = out.File
	file_qwibi_geojson_proto_rawDesc = nil
	file_qwibi_geojson_proto_goTypes = nil
	file_qwibi_geojson_proto_depIdxs = nil
}
