// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: qwibi/geometry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QPBxLayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QPBxLayer) Reset() {
	*x = QPBxLayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qwibi_geometry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxLayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxLayer) ProtoMessage() {}

func (x *QPBxLayer) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_geometry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxLayer.ProtoReflect.Descriptor instead.
func (*QPBxLayer) Descriptor() ([]byte, []int) {
	return file_qwibi_geometry_proto_rawDescGZIP(), []int{0}
}

type QPBxPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []float64 `protobuf:"fixed64,1,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *QPBxPoint) Reset() {
	*x = QPBxPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qwibi_geometry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxPoint) ProtoMessage() {}

func (x *QPBxPoint) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_geometry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxPoint.ProtoReflect.Descriptor instead.
func (*QPBxPoint) Descriptor() ([]byte, []int) {
	return file_qwibi_geometry_proto_rawDescGZIP(), []int{1}
}

func (x *QPBxPoint) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type QPBxLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*QPBxPoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *QPBxLine) Reset() {
	*x = QPBxLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qwibi_geometry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxLine) ProtoMessage() {}

func (x *QPBxLine) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_geometry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxLine.ProtoReflect.Descriptor instead.
func (*QPBxLine) Descriptor() ([]byte, []int) {
	return file_qwibi_geometry_proto_rawDescGZIP(), []int{2}
}

func (x *QPBxLine) GetPoints() []*QPBxPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_qwibi_geometry_proto protoreflect.FileDescriptor

var file_qwibi_geometry_proto_rawDesc = []byte{
	0x0a, 0x14, 0x71, 0x77, 0x69, 0x62, 0x69, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x09, 0x51, 0x50, 0x42, 0x78, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x22, 0x2e, 0x0a, 0x08, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x22,
	0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x51, 0x50, 0x42, 0x78, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qwibi_geometry_proto_rawDescOnce sync.Once
	file_qwibi_geometry_proto_rawDescData = file_qwibi_geometry_proto_rawDesc
)

func file_qwibi_geometry_proto_rawDescGZIP() []byte {
	file_qwibi_geometry_proto_rawDescOnce.Do(func() {
		file_qwibi_geometry_proto_rawDescData = protoimpl.X.CompressGZIP(file_qwibi_geometry_proto_rawDescData)
	})
	return file_qwibi_geometry_proto_rawDescData
}

var file_qwibi_geometry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_qwibi_geometry_proto_goTypes = []interface{}{
	(*QPBxLayer)(nil), // 0: QPBxLayer
	(*QPBxPoint)(nil), // 1: QPBxPoint
	(*QPBxLine)(nil),  // 2: QPBxLine
}
var file_qwibi_geometry_proto_depIdxs = []int32{
	1, // 0: QPBxLine.points:type_name -> QPBxPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_qwibi_geometry_proto_init() }
func file_qwibi_geometry_proto_init() {
	if File_qwibi_geometry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qwibi_geometry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxLayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qwibi_geometry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qwibi_geometry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qwibi_geometry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_geometry_proto_goTypes,
		DependencyIndexes: file_qwibi_geometry_proto_depIdxs,
		MessageInfos:      file_qwibi_geometry_proto_msgTypes,
	}.Build()
	File_qwibi_geometry_proto = out.File
	file_qwibi_geometry_proto_rawDesc = nil
	file_qwibi_geometry_proto_goTypes = nil
	file_qwibi_geometry_proto_depIdxs = nil
}
