// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qwibi/join.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QPBxJoinRequest struct {
	LayerID              string   `protobuf:"bytes,1,opt,name=layerID,proto3" json:"layerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QPBxJoinRequest) Reset()         { *m = QPBxJoinRequest{} }
func (m *QPBxJoinRequest) String() string { return proto.CompactTextString(m) }
func (*QPBxJoinRequest) ProtoMessage()    {}
func (*QPBxJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f14cbc5c03828f, []int{0}
}

func (m *QPBxJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QPBxJoinRequest.Unmarshal(m, b)
}
func (m *QPBxJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QPBxJoinRequest.Marshal(b, m, deterministic)
}
func (m *QPBxJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QPBxJoinRequest.Merge(m, src)
}
func (m *QPBxJoinRequest) XXX_Size() int {
	return xxx_messageInfo_QPBxJoinRequest.Size(m)
}
func (m *QPBxJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QPBxJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QPBxJoinRequest proto.InternalMessageInfo

func (m *QPBxJoinRequest) GetLayerID() string {
	if m != nil {
		return m.LayerID
	}
	return ""
}

type QPBxJoinResponse struct {
	Layer                *QPBxLayer `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QPBxJoinResponse) Reset()         { *m = QPBxJoinResponse{} }
func (m *QPBxJoinResponse) String() string { return proto.CompactTextString(m) }
func (*QPBxJoinResponse) ProtoMessage()    {}
func (*QPBxJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_43f14cbc5c03828f, []int{1}
}

func (m *QPBxJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QPBxJoinResponse.Unmarshal(m, b)
}
func (m *QPBxJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QPBxJoinResponse.Marshal(b, m, deterministic)
}
func (m *QPBxJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QPBxJoinResponse.Merge(m, src)
}
func (m *QPBxJoinResponse) XXX_Size() int {
	return xxx_messageInfo_QPBxJoinResponse.Size(m)
}
func (m *QPBxJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QPBxJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QPBxJoinResponse proto.InternalMessageInfo

func (m *QPBxJoinResponse) GetLayer() *QPBxLayer {
	if m != nil {
		return m.Layer
	}
	return nil
}

func init() {
	proto.RegisterType((*QPBxJoinRequest)(nil), "QPBxJoinRequest")
	proto.RegisterType((*QPBxJoinResponse)(nil), "QPBxJoinResponse")
}

func init() {
	proto.RegisterFile("qwibi/join.proto", fileDescriptor_43f14cbc5c03828f)
}

var fileDescriptor_43f14cbc5c03828f = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2c, 0xcf, 0x4c,
	0xca, 0xd4, 0xcf, 0xca, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x12, 0x84, 0x88,
	0xe4, 0x24, 0x56, 0xa6, 0x16, 0x41, 0x84, 0x94, 0xb4, 0xb9, 0xf8, 0x03, 0x03, 0x9c, 0x2a, 0xbc,
	0xf2, 0x33, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb8, 0xd8, 0xc1, 0x2a,
	0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x13, 0x2e, 0x01, 0x84,
	0xe2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x05, 0x2e, 0x56, 0xb0, 0x34, 0x58, 0x2d, 0xb7,
	0x11, 0x97, 0x1e, 0x48, 0x85, 0x0f, 0x48, 0x24, 0x08, 0x22, 0xe1, 0xc4, 0x1b, 0xc5, 0x0d, 0xb6,
	0xcb, 0x1a, 0x4c, 0x26, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xb5,
	0xec, 0xf6, 0x9f, 0x00, 0x00, 0x00,
}
