// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qwibi/layer.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QPBxLayer struct {
	LayerID              string   `protobuf:"bytes,1,opt,name=layerID,proto3" json:"layerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QPBxLayer) Reset()         { *m = QPBxLayer{} }
func (m *QPBxLayer) String() string { return proto.CompactTextString(m) }
func (*QPBxLayer) ProtoMessage()    {}
func (*QPBxLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_10ec98626f435969, []int{0}
}

func (m *QPBxLayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QPBxLayer.Unmarshal(m, b)
}
func (m *QPBxLayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QPBxLayer.Marshal(b, m, deterministic)
}
func (m *QPBxLayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QPBxLayer.Merge(m, src)
}
func (m *QPBxLayer) XXX_Size() int {
	return xxx_messageInfo_QPBxLayer.Size(m)
}
func (m *QPBxLayer) XXX_DiscardUnknown() {
	xxx_messageInfo_QPBxLayer.DiscardUnknown(m)
}

var xxx_messageInfo_QPBxLayer proto.InternalMessageInfo

func (m *QPBxLayer) GetLayerID() string {
	if m != nil {
		return m.LayerID
	}
	return ""
}

func (m *QPBxLayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*QPBxLayer)(nil), "QPBxLayer")
}

func init() {
	proto.RegisterFile("qwibi/layer.proto", fileDescriptor_10ec98626f435969)
}

var fileDescriptor_10ec98626f435969 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2c, 0xcf, 0x4c,
	0xca, 0xd4, 0xcf, 0x49, 0xac, 0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe4,
	0xe2, 0x0c, 0x0c, 0x70, 0xaa, 0xf0, 0x01, 0x09, 0x09, 0x49, 0x70, 0xb1, 0x83, 0xe5, 0x3c, 0x5d,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc,
	0x54, 0x09, 0x26, 0xb0, 0x30, 0x98, 0xed, 0xc4, 0x1b, 0xc5, 0x0d, 0x36, 0xc3, 0x1a, 0x4c, 0x26,
	0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x4a, 0xa4, 0xa4, 0x65, 0x00,
	0x00, 0x00,
}
