// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / Auth
type QPBxAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Auth:
	//
	//	*QPBxAuthRequest_Anonym
	//	*QPBxAuthRequest_Basic
	Auth isQPBxAuthRequest_Auth `protobuf_oneof:"auth"`
}

func (x *QPBxAuthRequest) Reset() {
	*x = QPBxAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxAuthRequest) ProtoMessage() {}

func (x *QPBxAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxAuthRequest.ProtoReflect.Descriptor instead.
func (*QPBxAuthRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (m *QPBxAuthRequest) GetAuth() isQPBxAuthRequest_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (x *QPBxAuthRequest) GetAnonym() *QPBxAnonymAuth {
	if x, ok := x.GetAuth().(*QPBxAuthRequest_Anonym); ok {
		return x.Anonym
	}
	return nil
}

func (x *QPBxAuthRequest) GetBasic() *QPBxBasicAuth {
	if x, ok := x.GetAuth().(*QPBxAuthRequest_Basic); ok {
		return x.Basic
	}
	return nil
}

type isQPBxAuthRequest_Auth interface {
	isQPBxAuthRequest_Auth()
}

type QPBxAuthRequest_Anonym struct {
	Anonym *QPBxAnonymAuth `protobuf:"bytes,1,opt,name=anonym,proto3,oneof"`
}

type QPBxAuthRequest_Basic struct {
	Basic *QPBxBasicAuth `protobuf:"bytes,2,opt,name=basic,proto3,oneof"`
}

func (*QPBxAuthRequest_Anonym) isQPBxAuthRequest_Auth() {}

func (*QPBxAuthRequest_Basic) isQPBxAuthRequest_Auth() {}

type QPBxAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *QPBxSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *QPBxAuthResponse) Reset() {
	*x = QPBxAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxAuthResponse) ProtoMessage() {}

func (x *QPBxAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxAuthResponse.ProtoReflect.Descriptor instead.
func (*QPBxAuthResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *QPBxAuthResponse) GetSession() *QPBxSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// / Token
type QPBxTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LayerId string `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
}

func (x *QPBxTokenRequest) Reset() {
	*x = QPBxTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxTokenRequest) ProtoMessage() {}

func (x *QPBxTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxTokenRequest.ProtoReflect.Descriptor instead.
func (*QPBxTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *QPBxTokenRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

type QPBxTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *QPBxTokenResponse) Reset() {
	*x = QPBxTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxTokenResponse) ProtoMessage() {}

func (x *QPBxTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxTokenResponse.ProtoReflect.Descriptor instead.
func (*QPBxTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *QPBxTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Layer
type QPBxLayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LayerId    string            `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	Public     bool              `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	Properties []byte            `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	Commands   map[string]string `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *QPBxLayerRequest) Reset() {
	*x = QPBxLayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxLayerRequest) ProtoMessage() {}

func (x *QPBxLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxLayerRequest.ProtoReflect.Descriptor instead.
func (*QPBxLayerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *QPBxLayerRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *QPBxLayerRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *QPBxLayerRequest) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *QPBxLayerRequest) GetCommands() map[string]string {
	if x != nil {
		return x.Commands
	}
	return nil
}

type QPBxLayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer *QPBxGeoLayer `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *QPBxLayerResponse) Reset() {
	*x = QPBxLayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxLayerResponse) ProtoMessage() {}

func (x *QPBxLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxLayerResponse.ProtoReflect.Descriptor instead.
func (*QPBxLayerResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *QPBxLayerResponse) GetLayer() *QPBxGeoLayer {
	if x != nil {
		return x.Layer
	}
	return nil
}

// Post
type QPBxPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LayerId string         `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	Object  *QPBxGeoObject `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *QPBxPostRequest) Reset() {
	*x = QPBxPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxPostRequest) ProtoMessage() {}

func (x *QPBxPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxPostRequest.ProtoReflect.Descriptor instead.
func (*QPBxPostRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *QPBxPostRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *QPBxPostRequest) GetObject() *QPBxGeoObject {
	if x != nil {
		return x.Object
	}
	return nil
}

type QPBxPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *QPBxPostResponse) Reset() {
	*x = QPBxPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxPostResponse) ProtoMessage() {}

func (x *QPBxPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxPostResponse.ProtoReflect.Descriptor instead.
func (*QPBxPostResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *QPBxPostResponse) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

// / Get
type QPBxGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *QPBxGetRequest) Reset() {
	*x = QPBxGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxGetRequest) ProtoMessage() {}

func (x *QPBxGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxGetRequest.ProtoReflect.Descriptor instead.
func (*QPBxGetRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *QPBxGetRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type QPBxGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object *QPBxGeoObject `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *QPBxGetResponse) Reset() {
	*x = QPBxGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxGetResponse) ProtoMessage() {}

func (x *QPBxGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxGetResponse.ProtoReflect.Descriptor instead.
func (*QPBxGetResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *QPBxGetResponse) GetObject() *QPBxGeoObject {
	if x != nil {
		return x.Object
	}
	return nil
}

// / Command
type QPBxCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string       `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LayerId   string       `protobuf:"bytes,2,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	Command   *QPBxCommand `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *QPBxCommandRequest) Reset() {
	*x = QPBxCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxCommandRequest) ProtoMessage() {}

func (x *QPBxCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxCommandRequest.ProtoReflect.Descriptor instead.
func (*QPBxCommandRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *QPBxCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QPBxCommandRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *QPBxCommandRequest) GetCommand() *QPBxCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type QPBxCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string        `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LayerId   string        `protobuf:"bytes,2,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	Response  *QPBxResponse `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *QPBxCommandResponse) Reset() {
	*x = QPBxCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxCommandResponse) ProtoMessage() {}

func (x *QPBxCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxCommandResponse.ProtoReflect.Descriptor instead.
func (*QPBxCommandResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *QPBxCommandResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QPBxCommandResponse) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *QPBxCommandResponse) GetResponse() *QPBxResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

// / Stream
type QPBxStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *QPBxEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *QPBxStreamRequest) Reset() {
	*x = QPBxStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxStreamRequest) ProtoMessage() {}

func (x *QPBxStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxStreamRequest.ProtoReflect.Descriptor instead.
func (*QPBxStreamRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *QPBxStreamRequest) GetEvent() *QPBxEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type QPBxStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *QPBxEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *QPBxStreamResponse) Reset() {
	*x = QPBxStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxStreamResponse) ProtoMessage() {}

func (x *QPBxStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxStreamResponse.ProtoReflect.Descriptor instead.
func (*QPBxStreamResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *QPBxStreamResponse) GetEvent() *QPBxEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type QPBxEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*QPBxEvent_AuthRequest
	//	*QPBxEvent_LayerRequest
	//	*QPBxEvent_CommandRequest
	//	*QPBxEvent_AuthResponse
	//	*QPBxEvent_LayerResponse
	//	*QPBxEvent_CommandResponse
	Type isQPBxEvent_Type `protobuf_oneof:"type"`
}

func (x *QPBxEvent) Reset() {
	*x = QPBxEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QPBxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QPBxEvent) ProtoMessage() {}

func (x *QPBxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QPBxEvent.ProtoReflect.Descriptor instead.
func (*QPBxEvent) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (m *QPBxEvent) GetType() isQPBxEvent_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *QPBxEvent) GetAuthRequest() *QPBxAuthRequest {
	if x, ok := x.GetType().(*QPBxEvent_AuthRequest); ok {
		return x.AuthRequest
	}
	return nil
}

func (x *QPBxEvent) GetLayerRequest() *QPBxLayerRequest {
	if x, ok := x.GetType().(*QPBxEvent_LayerRequest); ok {
		return x.LayerRequest
	}
	return nil
}

func (x *QPBxEvent) GetCommandRequest() *QPBxCommandRequest {
	if x, ok := x.GetType().(*QPBxEvent_CommandRequest); ok {
		return x.CommandRequest
	}
	return nil
}

func (x *QPBxEvent) GetAuthResponse() *QPBxAuthResponse {
	if x, ok := x.GetType().(*QPBxEvent_AuthResponse); ok {
		return x.AuthResponse
	}
	return nil
}

func (x *QPBxEvent) GetLayerResponse() *QPBxLayerResponse {
	if x, ok := x.GetType().(*QPBxEvent_LayerResponse); ok {
		return x.LayerResponse
	}
	return nil
}

func (x *QPBxEvent) GetCommandResponse() *QPBxCommandResponse {
	if x, ok := x.GetType().(*QPBxEvent_CommandResponse); ok {
		return x.CommandResponse
	}
	return nil
}

type isQPBxEvent_Type interface {
	isQPBxEvent_Type()
}

type QPBxEvent_AuthRequest struct {
	AuthRequest *QPBxAuthRequest `protobuf:"bytes,11,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type QPBxEvent_LayerRequest struct {
	LayerRequest *QPBxLayerRequest `protobuf:"bytes,12,opt,name=layer_request,json=layerRequest,proto3,oneof"`
}

type QPBxEvent_CommandRequest struct {
	CommandRequest *QPBxCommandRequest `protobuf:"bytes,13,opt,name=command_request,json=commandRequest,proto3,oneof"`
}

type QPBxEvent_AuthResponse struct {
	AuthResponse *QPBxAuthResponse `protobuf:"bytes,21,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type QPBxEvent_LayerResponse struct {
	LayerResponse *QPBxLayerResponse `protobuf:"bytes,22,opt,name=layer_response,json=layerResponse,proto3,oneof"`
}

type QPBxEvent_CommandResponse struct {
	CommandResponse *QPBxCommandResponse `protobuf:"bytes,23,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

func (*QPBxEvent_AuthRequest) isQPBxEvent_Type() {}

func (*QPBxEvent_LayerRequest) isQPBxEvent_Type() {}

func (*QPBxEvent_CommandRequest) isQPBxEvent_Type() {}

func (*QPBxEvent_AuthResponse) isQPBxEvent_Type() {}

func (*QPBxEvent_LayerResponse) isQPBxEvent_Type() {}

func (*QPBxEvent_CommandResponse) isQPBxEvent_Type() {}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0a, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x67, 0x65, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x0f, 0x51, 0x50, 0x42, 0x78, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x6e, 0x6f, 0x6e,
	0x79, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x41,
	0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x06, 0x61, 0x6e, 0x6f,
	0x6e, 0x79, 0x6d, 0x12, 0x26, 0x0a, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75,
	0x74, 0x68, 0x48, 0x00, 0x52, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x42, 0x06, 0x0a, 0x04, 0x61,
	0x75, 0x74, 0x68, 0x22, 0x3a, 0x0a, 0x10, 0x51, 0x50, 0x42, 0x78, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x2d, 0x0a, 0x10, 0x51, 0x50, 0x42, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x29,
	0x0a, 0x11, 0x51, 0x50, 0x42, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xdf, 0x01, 0x0a, 0x10, 0x51, 0x50,
	0x42, 0x78, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x3b, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x1a, 0x3b,
	0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x38, 0x0a, 0x11, 0x51,
	0x50, 0x42, 0x78, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x47, 0x65, 0x6f, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x05,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x0f, 0x51, 0x50, 0x42, 0x78, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x47, 0x65, 0x6f, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x24, 0x0a, 0x10, 0x51,
	0x50, 0x42, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69,
	0x64, 0x22, 0x22, 0x0a, 0x0e, 0x51, 0x50, 0x42, 0x78, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x67, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x0f, 0x51, 0x50, 0x42, 0x78, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x47,
	0x65, 0x6f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x22, 0x76, 0x0a, 0x12, 0x51, 0x50, 0x42, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x7a, 0x0a, 0x13, 0x51, 0x50, 0x42, 0x78,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x51, 0x50,
	0x42, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x0a, 0x11, 0x51, 0x50, 0x42, 0x78, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x12, 0x51,
	0x50, 0x42, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0xfe, 0x02, 0x0a, 0x09, 0x51, 0x50, 0x42, 0x78, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x35, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0d, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x51, 0x50,
	0x42, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x51, 0x50, 0x42, 0x78,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c,
	0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0e,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x16,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x10, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x17, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x32, 0x90, 0x03, 0x0a, 0x07, 0x51, 0x50, 0x42, 0x78, 0x41, 0x70, 0x69,
	0x12, 0x2b, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x10, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x51, 0x50, 0x42,
	0x78, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x05, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x51, 0x50, 0x42, 0x78,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x0f, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x11, 0x2e,
	0x51, 0x50, 0x42, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x13, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x03, 0x42, 0x6f,
	0x74, 0x12, 0x14, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x13, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x35, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x51, 0x50, 0x42,
	0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x51, 0x50, 0x42, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_service_proto_goTypes = []interface{}{
	(*QPBxAuthRequest)(nil),     // 0: QPBxAuthRequest
	(*QPBxAuthResponse)(nil),    // 1: QPBxAuthResponse
	(*QPBxTokenRequest)(nil),    // 2: QPBxTokenRequest
	(*QPBxTokenResponse)(nil),   // 3: QPBxTokenResponse
	(*QPBxLayerRequest)(nil),    // 4: QPBxLayerRequest
	(*QPBxLayerResponse)(nil),   // 5: QPBxLayerResponse
	(*QPBxPostRequest)(nil),     // 6: QPBxPostRequest
	(*QPBxPostResponse)(nil),    // 7: QPBxPostResponse
	(*QPBxGetRequest)(nil),      // 8: QPBxGetRequest
	(*QPBxGetResponse)(nil),     // 9: QPBxGetResponse
	(*QPBxCommandRequest)(nil),  // 10: QPBxCommandRequest
	(*QPBxCommandResponse)(nil), // 11: QPBxCommandResponse
	(*QPBxStreamRequest)(nil),   // 12: QPBxStreamRequest
	(*QPBxStreamResponse)(nil),  // 13: QPBxStreamResponse
	(*QPBxEvent)(nil),           // 14: QPBxEvent
	nil,                         // 15: QPBxLayerRequest.CommandsEntry
	(*QPBxAnonymAuth)(nil),      // 16: QPBxAnonymAuth
	(*QPBxBasicAuth)(nil),       // 17: QPBxBasicAuth
	(*QPBxSession)(nil),         // 18: QPBxSession
	(*QPBxGeoLayer)(nil),        // 19: QPBxGeoLayer
	(*QPBxGeoObject)(nil),       // 20: QPBxGeoObject
	(*QPBxCommand)(nil),         // 21: QPBxCommand
	(*QPBxResponse)(nil),        // 22: QPBxResponse
}
var file_service_proto_depIdxs = []int32{
	16, // 0: QPBxAuthRequest.anonym:type_name -> QPBxAnonymAuth
	17, // 1: QPBxAuthRequest.basic:type_name -> QPBxBasicAuth
	18, // 2: QPBxAuthResponse.session:type_name -> QPBxSession
	15, // 3: QPBxLayerRequest.commands:type_name -> QPBxLayerRequest.CommandsEntry
	19, // 4: QPBxLayerResponse.layer:type_name -> QPBxGeoLayer
	20, // 5: QPBxPostRequest.object:type_name -> QPBxGeoObject
	20, // 6: QPBxGetResponse.object:type_name -> QPBxGeoObject
	21, // 7: QPBxCommandRequest.command:type_name -> QPBxCommand
	22, // 8: QPBxCommandResponse.response:type_name -> QPBxResponse
	14, // 9: QPBxStreamRequest.event:type_name -> QPBxEvent
	14, // 10: QPBxStreamResponse.event:type_name -> QPBxEvent
	0,  // 11: QPBxEvent.auth_request:type_name -> QPBxAuthRequest
	4,  // 12: QPBxEvent.layer_request:type_name -> QPBxLayerRequest
	10, // 13: QPBxEvent.command_request:type_name -> QPBxCommandRequest
	1,  // 14: QPBxEvent.auth_response:type_name -> QPBxAuthResponse
	5,  // 15: QPBxEvent.layer_response:type_name -> QPBxLayerResponse
	11, // 16: QPBxEvent.command_response:type_name -> QPBxCommandResponse
	0,  // 17: QPBxApi.Auth:input_type -> QPBxAuthRequest
	4,  // 18: QPBxApi.Layer:input_type -> QPBxLayerRequest
	6,  // 19: QPBxApi.Post:input_type -> QPBxPostRequest
	8,  // 20: QPBxApi.Get:input_type -> QPBxGetRequest
	2,  // 21: QPBxApi.Token:input_type -> QPBxTokenRequest
	10, // 22: QPBxApi.Command:input_type -> QPBxCommandRequest
	11, // 23: QPBxApi.Bot:input_type -> QPBxCommandResponse
	12, // 24: QPBxApi.Stream:input_type -> QPBxStreamRequest
	1,  // 25: QPBxApi.Auth:output_type -> QPBxAuthResponse
	5,  // 26: QPBxApi.Layer:output_type -> QPBxLayerResponse
	7,  // 27: QPBxApi.Post:output_type -> QPBxPostResponse
	9,  // 28: QPBxApi.Get:output_type -> QPBxGetResponse
	3,  // 29: QPBxApi.Token:output_type -> QPBxTokenResponse
	11, // 30: QPBxApi.Command:output_type -> QPBxCommandResponse
	10, // 31: QPBxApi.Bot:output_type -> QPBxCommandRequest
	13, // 32: QPBxApi.Stream:output_type -> QPBxStreamResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_auth_proto_init()
	file_geo_proto_init()
	file_command_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxLayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxLayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QPBxEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*QPBxAuthRequest_Anonym)(nil),
		(*QPBxAuthRequest_Basic)(nil),
	}
	file_service_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*QPBxEvent_AuthRequest)(nil),
		(*QPBxEvent_LayerRequest)(nil),
		(*QPBxEvent_CommandRequest)(nil),
		(*QPBxEvent_AuthResponse)(nil),
		(*QPBxEvent_LayerResponse)(nil),
		(*QPBxEvent_CommandResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
