// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: qwibi/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_qwibi_service_proto protoreflect.FileDescriptor

var file_qwibi_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x77, 0x69, 0x62, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x71, 0x77, 0x69, 0x62, 0x69, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x71, 0x77, 0x69, 0x62, 0x69, 0x2f, 0x6a,
	0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x71, 0x77, 0x69, 0x62, 0x69,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10,
	0x71, 0x77, 0x69, 0x62, 0x69, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x71, 0x77, 0x69, 0x62, 0x69, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x32, 0xfd, 0x01, 0x0a, 0x07, 0x51, 0x50, 0x42, 0x78, 0x41, 0x70, 0x69,
	0x12, 0x2b, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x10, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x51, 0x50, 0x42,
	0x78, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x51, 0x50, 0x42,
	0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x51, 0x50, 0x42,
	0x78, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x51, 0x50, 0x42, 0x78, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x51, 0x50,
	0x42, 0x78, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_qwibi_service_proto_goTypes = []interface{}{
	(*QPBxAuthRequest)(nil),     // 0: QPBxAuthRequest
	(*QPBxJoinRequest)(nil),     // 1: QPBxJoinRequest
	(*QPBxMessageRequest)(nil),  // 2: QPBxMessageRequest
	(*QPBxPostRequest)(nil),     // 3: QPBxPostRequest
	(*QPBxStreamRequest)(nil),   // 4: QPBxStreamRequest
	(*QPBxAuthResponse)(nil),    // 5: QPBxAuthResponse
	(*QPBxJoinResponse)(nil),    // 6: QPBxJoinResponse
	(*QPBxMessageResponse)(nil), // 7: QPBxMessageResponse
	(*QPBxPostResponse)(nil),    // 8: QPBxPostResponse
	(*QPBxStreamResponse)(nil),  // 9: QPBxStreamResponse
}
var file_qwibi_service_proto_depIdxs = []int32{
	0, // 0: QPBxApi.Auth:input_type -> QPBxAuthRequest
	1, // 1: QPBxApi.Join:input_type -> QPBxJoinRequest
	2, // 2: QPBxApi.Message:input_type -> QPBxMessageRequest
	3, // 3: QPBxApi.Post:input_type -> QPBxPostRequest
	4, // 4: QPBxApi.Stream:input_type -> QPBxStreamRequest
	5, // 5: QPBxApi.Auth:output_type -> QPBxAuthResponse
	6, // 6: QPBxApi.Join:output_type -> QPBxJoinResponse
	7, // 7: QPBxApi.Message:output_type -> QPBxMessageResponse
	8, // 8: QPBxApi.Post:output_type -> QPBxPostResponse
	9, // 9: QPBxApi.Stream:output_type -> QPBxStreamResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qwibi_service_proto_init() }
func file_qwibi_service_proto_init() {
	if File_qwibi_service_proto != nil {
		return
	}
	file_qwibi_auth_proto_init()
	file_qwibi_join_proto_init()
	file_qwibi_message_proto_init()
	file_qwibi_post_proto_init()
	file_qwibi_stream_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qwibi_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qwibi_service_proto_goTypes,
		DependencyIndexes: file_qwibi_service_proto_depIdxs,
	}.Build()
	File_qwibi_service_proto = out.File
	file_qwibi_service_proto_rawDesc = nil
	file_qwibi_service_proto_goTypes = nil
	file_qwibi_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QPBxApiClient is the client API for QPBxApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QPBxApiClient interface {
	// AUTH return authToken
	Auth(ctx context.Context, in *QPBxAuthRequest, opts ...grpc.CallOption) (*QPBxAuthResponse, error)
	// Join to layer
	Join(ctx context.Context, in *QPBxJoinRequest, opts ...grpc.CallOption) (*QPBxJoinResponse, error)
	// Message
	Message(ctx context.Context, in *QPBxMessageRequest, opts ...grpc.CallOption) (*QPBxMessageResponse, error)
	// Post
	Post(ctx context.Context, in *QPBxPostRequest, opts ...grpc.CallOption) (*QPBxPostResponse, error)
	// Stream
	Stream(ctx context.Context, opts ...grpc.CallOption) (QPBxApi_StreamClient, error)
}

type qPBxApiClient struct {
	cc grpc.ClientConnInterface
}

func NewQPBxApiClient(cc grpc.ClientConnInterface) QPBxApiClient {
	return &qPBxApiClient{cc}
}

func (c *qPBxApiClient) Auth(ctx context.Context, in *QPBxAuthRequest, opts ...grpc.CallOption) (*QPBxAuthResponse, error) {
	out := new(QPBxAuthResponse)
	err := c.cc.Invoke(ctx, "/QPBxApi/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPBxApiClient) Join(ctx context.Context, in *QPBxJoinRequest, opts ...grpc.CallOption) (*QPBxJoinResponse, error) {
	out := new(QPBxJoinResponse)
	err := c.cc.Invoke(ctx, "/QPBxApi/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPBxApiClient) Message(ctx context.Context, in *QPBxMessageRequest, opts ...grpc.CallOption) (*QPBxMessageResponse, error) {
	out := new(QPBxMessageResponse)
	err := c.cc.Invoke(ctx, "/QPBxApi/Message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPBxApiClient) Post(ctx context.Context, in *QPBxPostRequest, opts ...grpc.CallOption) (*QPBxPostResponse, error) {
	out := new(QPBxPostResponse)
	err := c.cc.Invoke(ctx, "/QPBxApi/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qPBxApiClient) Stream(ctx context.Context, opts ...grpc.CallOption) (QPBxApi_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QPBxApi_serviceDesc.Streams[0], "/QPBxApi/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &qPBxApiStreamClient{stream}
	return x, nil
}

type QPBxApi_StreamClient interface {
	Send(*QPBxStreamRequest) error
	Recv() (*QPBxStreamResponse, error)
	grpc.ClientStream
}

type qPBxApiStreamClient struct {
	grpc.ClientStream
}

func (x *qPBxApiStreamClient) Send(m *QPBxStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *qPBxApiStreamClient) Recv() (*QPBxStreamResponse, error) {
	m := new(QPBxStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QPBxApiServer is the server API for QPBxApi service.
type QPBxApiServer interface {
	// AUTH return authToken
	Auth(context.Context, *QPBxAuthRequest) (*QPBxAuthResponse, error)
	// Join to layer
	Join(context.Context, *QPBxJoinRequest) (*QPBxJoinResponse, error)
	// Message
	Message(context.Context, *QPBxMessageRequest) (*QPBxMessageResponse, error)
	// Post
	Post(context.Context, *QPBxPostRequest) (*QPBxPostResponse, error)
	// Stream
	Stream(QPBxApi_StreamServer) error
}

// UnimplementedQPBxApiServer can be embedded to have forward compatible implementations.
type UnimplementedQPBxApiServer struct {
}

func (*UnimplementedQPBxApiServer) Auth(context.Context, *QPBxAuthRequest) (*QPBxAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedQPBxApiServer) Join(context.Context, *QPBxJoinRequest) (*QPBxJoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedQPBxApiServer) Message(context.Context, *QPBxMessageRequest) (*QPBxMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}
func (*UnimplementedQPBxApiServer) Post(context.Context, *QPBxPostRequest) (*QPBxPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (*UnimplementedQPBxApiServer) Stream(QPBxApi_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterQPBxApiServer(s *grpc.Server, srv QPBxApiServer) {
	s.RegisterService(&_QPBxApi_serviceDesc, srv)
}

func _QPBxApi_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QPBxAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPBxApiServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QPBxApi/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPBxApiServer).Auth(ctx, req.(*QPBxAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPBxApi_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QPBxJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPBxApiServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QPBxApi/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPBxApiServer).Join(ctx, req.(*QPBxJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPBxApi_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QPBxMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPBxApiServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QPBxApi/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPBxApiServer).Message(ctx, req.(*QPBxMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPBxApi_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QPBxPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QPBxApiServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QPBxApi/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QPBxApiServer).Post(ctx, req.(*QPBxPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QPBxApi_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QPBxApiServer).Stream(&qPBxApiStreamServer{stream})
}

type QPBxApi_StreamServer interface {
	Send(*QPBxStreamResponse) error
	Recv() (*QPBxStreamRequest, error)
	grpc.ServerStream
}

type qPBxApiStreamServer struct {
	grpc.ServerStream
}

func (x *qPBxApiStreamServer) Send(m *QPBxStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *qPBxApiStreamServer) Recv() (*QPBxStreamRequest, error) {
	m := new(QPBxStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _QPBxApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "QPBxApi",
	HandlerType: (*QPBxApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _QPBxApi_Auth_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _QPBxApi_Join_Handler,
		},
		{
			MethodName: "Message",
			Handler:    _QPBxApi_Message_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _QPBxApi_Post_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _QPBxApi_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "qwibi/service.proto",
}
